stages:
  - package

# Job to create a zip file and attach it to a release
zip_files:
  stage: package
  script:
    # Create a folder for the zip output
    - mkdir -p kicad_assembly_generator_${CI_COMMIT_TAG}
    # List specific files you want to include in the zip
    - zip kicad_assembly_generator_${CI_COMMIT_TAG}.zip metadata.json resources plugins/*
  artifacts:
    paths:
      - kicad_assembly_generator_${CI_COMMIT_TAG}.zip
  only:
    - tags
  after_script:
    # Create a release and upload the artifact using GitLab's API
    - |
      curl --request POST --header "PRIVATE-TOKEN: $CI_JOB_TOKEN" \
        --form "name=Release ${CI_COMMIT_TAG}" \
        --form "tag_name=${CI_COMMIT_TAG}" \
        --form "ref=${CI_COMMIT_SHA}" \
        --form "description=Automated release for tag ${CI_COMMIT_TAG}" \
        --form "assets[links][][name]=Download release zip" \
        --form "assets[links][][url]=$CI_PROJECT_URL/-/jobs/$CI_JOB_ID/artifacts/download" \
        "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/releases"