stages:
  - package

# Job to zip plugin
zip_files:
  stage: package
  image: ruby:3.1
  before_script:
    # Install zip utility
    - apt-get update && apt-get install -y zip
  script:
    # Create a folder for the zip output
    - mkdir -p kicad_assembly_generator_${CI_COMMIT_TAG}
    # Create zip file
    - zip kicad_assembly_generator_${CI_COMMIT_TAG}.zip metadata.json resources/* plugins/*
  artifacts:
    paths:
      - kicad_assembly_generator_${CI_COMMIT_TAG}.zip
  only:
    - tags
